name: "quick download helper"
description: "downloads a file from given url to current working directory"
inputs:
  source_url:
    description: 'url to download a file from'
    required: true
  output_path:
    description: 'path of the output file'
    required: true
  output_file:
    description: 'name of the output file'
    required: true

runs:
  using: "composite"
  steps:
    - name: windows
      if: runner.os == 'Windows'
      working-directory: ${{ inputs.output_file }}
      shell: pwsh
      run: Invoke-WebRequest ${{ inputs.source_url }} -OutFile ${{ inputs.output_file }}
    
    
    - name: linux
      if: runner.os == 'Linux'
      working-directory: ${{ inputs.output_file }}
      shell: bash
      run: curl -o ${{ inputs.output_file }} ${{ inputs.source_url }}
    
    
    - name: macos
      if: runner.os == 'macOS'
      working-directory: ${{ inputs.output_file }}
      shell: bash
      run: curl -o ${{ inputs.output_file }} ${{ inputs.source_url }}
    
